### ISSUE TITLE
when using from_image at machine, converge without specified attritbue

### ISSUE THREAD

**Issue by cl-lab-k** [chef/chef-provisioning-docker#61]
Here is simple chef-provisioning-docker recipe.

```ruby
require 'chef/provisioning'

nginx_config = {
  'nginx' => {
    'port' => 8080,
    'user' => 'www-data',
    'group' => 'www-data',
  }
}

machine_image 'nginx_base' do
  recipe 'nginx::package'
  attributes nginx_config

  machine_options :docker_options => {
    :base_image => {
      :name       => 'ubuntu',
      :repository => 'ubuntu',
      :tag        => '14.04'
    }
  }
end

machine 'nginx_server' do
  from_image 'nginx_base'

  attribute %w[ nginx port ], 8888
  attribute %w[ nginx user ], 'root'
  attribute %w[ nginx group ], nil

  machine_options :docker_options => {
    :command => '/usr/sbin/nginx -g "daemon off;"'
  }
end
```

`nginx_base` image has below attributes:

- `node['nginx']['port']` = 8080
- `node['nginx']['user']` = 'www-data'
- `node['nging']['group']` = 'www-data'

`nginx_server` container **replaces** them with below attributes (I assume):

- `node['nginx']['port']` = 8888
- `node['nginx']['user']` = 'root'
- `node['nging']['group']` = nil

After converging above recipe, `nginx_server` container has **replaced** attributes:

```json
vagrant@vagrant:~/docker$ head nodes/nginx_server.json 
{
  "name": "nginx_server",
  "normal": {
    "tags": null,
    "nginx": {
      "port": 8888,
      "user": "root",
      "group": null
    },
    "chef_provisioning": {
vagrant@vagrant:~/docker$ 
```

But template has *original* attributes:

```nginx
vagrant@vagrant:~/docker$ docker exec a216e6f0301f cat /etc/nginx/sites-enabled/default
server {
  listen   8080;
  server_name  4bbb91bca063;

  access_log  /var/log/nginx/localhost.access.log;

  location / {
    root   /var/www/nginx-default;
    index  index.html index.htm;
  }
}
vagrant@vagrant:~/docker$
```

Is it bug or my misunderstanding how to use attribute?

**Comment by marc-** [comment]
This is expected behavior. Your `machine_image 'nginx_base'` resource converges docker images with specified arguments, i.e. during `recipe 'nginx::package'` execution template will use your variables. Please note, that `machine_image` resource doesn't produce node on chef server. Instead it keeps information about images in data bag `machine_image`(though, it doesn't contain attributes).
For `machine 'nginx_server'` specifying attributes without specifying recipe makes not much sense. Since you images `nginx_base` already has configured nginx site and it won't get overridden. In opposite to `machine_image`, `machine` does produce node on chef server and your attributes goes there.

**Comment by cl-lab-k** [comment]
thank you very much for your explanation of its detail.  i satisfy it.
